github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

image:
  file: .gitpod.Dockerfile

# Uncomment to run tasks
# tasks:

  # Uncomment task if you want to start services on launch
  # - name: start
  #   command: confluent local services start && gp sync-done start

  # Uncomment task if you want to create datagen connectors on launch
  # - name: datagen
  #   command: |
  #     gp sync-await start
      
  #     curl -i -X PUT -H "Content-Type:application/json" \
  #       http://localhost:8083/connectors/users/config \
  #       -d @connectors/connector-datagen-users.json
          
  #     curl -i -X PUT -H "Content-Type:application/json" \
  #       http://localhost:8083/connectors/trades/config \
  #       -d @connectors/connector-datagen-trades.json

  # Uncomment task if you want to log into a confluent cloud cluster.
  # Must have $CONFLUENT_CLOUD_EMAIL, CONFLUENT_CLOUD_PASSWORD, and $CCLOUD_ENV_ID defined in gitpod.io/variables and scoped to this repo
  # - name: ccloud
  #   command: confluent login --save && confluent environment use $CCLOUD_ENV_ID

ports:
  # zookeeper
  - port: 2181
    onOpen: ignore
    
  # Confluent Server (broker)
  - port: 9092
    onOpen: ignore
    
  # Confluent Server (REST)
  - port: 8090
    onOpen: ignore
    
  # Schema Registry
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
    
  # Kafka Connect
  - port: 8083
    onOpen: ignore
    
  # ksqlDB
  - port: 8088
    onOpen: ignore
    
  # Confluent Control Center
  - port: 9021
    onOpen: open-preview
    visibility: public
